### ISSUE TITLE
Not able to showLoadings on biplot

### ISSUE THREAD

**Issue by cejdan** [kevinblighe/PCAtools#52] opened 2022-04-29 18:44 UTC
Thanks for the useful tool. My issue currently is that I cannot show the loadings arrows on the biplot, despite the `p$loadings` data.frame being correct, I think. Please see the reproducible example below with the iris dataset:

```
library(PCAtools)
mat <- as.matrix(iris[1:4], rownames.force= TRUE)
mat_transpose = t(mat)
p <- PCAtools::pca(mat_transpose, center = TRUE, scale = TRUE)
PCAtools::biplot(p, showLoadings = TRUE)

p$loadings
str(p$loadings)
```
``` 
> PCAtools::biplot(p, showLoadings = TRUE)
Warning messages:
1: Removed 5 rows containing missing values (geom_segment). 
2: Removed 5 rows containing missing values (geom_label_repel). 


> p$loadings
                    PC1         PC2        PC3        PC4
Sepal.Length  0.5210659 -0.37741762  0.7195664  0.2612863
Sepal.Width  -0.2693474 -0.92329566 -0.2443818 -0.1235096
Petal.Length  0.5804131 -0.02449161 -0.1421264 -0.8014492
Petal.Width   0.5648565 -0.06694199 -0.6342727  0.5235971

> str(p$loadings)
'data.frame':	4 obs. of  4 variables:
 $ PC1: num  0.521 -0.269 0.58 0.565
 $ PC2: num  -0.3774 -0.9233 -0.0245 -0.0669
 $ PC3: num  0.72 -0.244 -0.142 -0.634
 $ PC4: num  0.261 -0.124 -0.801 0.524
```
![pca_biplot](https://user-images.githubusercontent.com/59983880/166007571-9424b041-db8b-4381-b180-8d99ca519ac4.png)

**Comment by KeelyDulmage** [comment] 2022-05-12 17:12
I am unable to post a reproducible example because of confidential data, but I too am having issues with loadings not show up. Specifically, for the same dataset I can show loadings for all biplots except the biplot between PC2 and PC3. I have the following errors:
`Warning: Removed 10 rows containing missing values (geom_segment).`
`Warning: Removed 10 rows containing missing values (geom_label_repel).`
This error is not corrected by increasing the max overlap (currently set to 100). There are only 21 datapoints in this set. This is the code that produces the correct plot for PC1 vs PC2:
`biplot(p, showLoadings = TRUE, colby = "Tissue", shape = "Group", legendPosition = "right", legendLabSize = 8, legendIconSize = 1, legendTitleSize = 8, axisLabSize = 8, max.overlaps = 40, ntopLoadings = 10, alphaLoadingsArrow = 0.5, 
    labSize = 1, pointSize = 1.5, sizeLoadingsNames = 2)`
And this is the code for the plot that doesn't show loadings for PC2 and PC3 on that same dataset:
`biplot(p, showLoadings = TRUE, x = "PC2", y = "PC3", colby = "Tissue", shape = "Group", legendPosition = "right", legendLabSize = 8, legendIconSize = 1, legendTitleSize = 8, max.overlaps = 100, axisLabSize = 8,  ntopLoadings = 10, labSize = 1.5, pointSize = 1.5, sizeLoadingsNames = 2)`

I am using version 2.8.0 with R 4.2.0

**Comment by kevinblighe** [comment] 2022-08-18 16:26
Hi @cejdan, this can be resolved by expanding the axes and / or modifying the value of `lengthLoadingsArrowsFactor `.

biplot(p, showLoadings = TRUE, lengthLoadingsArrowsFactor = 1.2, xlim = c(-7,7), ylim = c(-7,7))

![Sem título](https://user-images.githubusercontent.com/23179755/185445776-295b8220-7d8b-4bf2-bab1-0f08f1ec4244.png)

@KeelyDulmage , can you verify that this also solves the issue that you are facing?

**Comment by kevinblighe** [comment] 2022-08-18 16:45
Please tag me directly here if the issue still persists. Thanks both.
Kind regards,
Kevin

**Closed by kevinblighe** 2022-08-18 16:45 UTC
